### ISSUE TITLE
Switch to Discord.js

### ISSUE THREAD

**Issue by LordNature** [BytewaveMLP/HappeningsBot#1]
Node.js is the future! Asynchronous compute!

**Comment by BytewaveMLP** [comment]
Hissssss...

**Comment by antigravities** [comment]
Wow, rude. Not even considering the Master Language for this project. I rate 0/10

**Comment by BytewaveMLP** [comment]
I should rewrite this in COBOL. Then we'll see who's laughing.

**Comment by LordNature** [comment]
@BytewaveMLP Do it. You won't.

**Comment by BytewaveMLP** [comment]
Does COBOL even support networking? O.o

**Comment by BytewaveMLP** [comment]
https://stackoverflow.com/questions/2625416/sockets-and-cobol

Oh god.

Nigga I ain't about to write an entire HTTP client to do this shit lol.

**Comment by antigravities** [comment]
Don't let your dreams be memes

Can't wait for BytewaveMLP/CoolCobolHTTPClient

**Comment by BytewaveMLP** [comment]
Please no..

**Comment by antigravities** [comment]
Please yes..

Just hook into libcurl, you don't even need to reinvent the wheel

![i'm in](https://eet.li/5de2ea3.png)
